- index.js
To be able to redefine the `runtimeCaching` prop should be defined as `let`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/shadowwalker/next-pwa/21)
> fix[main]: define runtimeCaching as let variable

- README.md
- index.js
added `subdomainPrefix` to support an app hosted on a subdomain
This is to correct the inappropriate naming in this pull request: https://github.com/shadowwalker/next-pwa/pull/31
a working example github pages with pwa (after locally modified next-pwa package): https://project-setup.github.io/github_pwa/
my pwa setup for the project: https://github.com/Project-Setup/github_pwa#pwa
> Add subdomain support

- index.js
Currently getRevision uses the file name instead of the file content to calculate the md5. This causes the revision in the sw.js manifest to always remain the same which in itself makes the cache not work as expected when there are changes in the file.
Closes #59
> Change getRevision to use file content not name

- README.md
- index.js
As mentioned in this [comment](https://github.com/shadowwalker/next-pwa/issues/64#issuecomment-645711907), sometimes there are some issues when precaching the home page. So, imo it would be good to set this home page precaching as an optional parameter for next-pwa.
If the user does not want to pre-cache it, now there's this optional param available.
> Add precache home page as optional

- cache.js
I get this error when try to use next-pwa.
```
Failed to compile.                                                                                                                                      
Please check your GenerateSW plugin configuration:                                                                                                      
child "runtimeCaching" fails because ["runtimeCaching" at position 8 fails because ["networkTimeoutSeconds" is not a supported parameter.]]
```
> Fix bug in the Cache.js

- register.js
The register.js is included in main.js and is not transpiled to target ES version. This causes IE to fail during parsing.
Rewrote the activated event listener to use ES5 syntax
> Rewrite activated event listener to ES5

- examples/lifecycle/pages/index.js
Since Workbox v6, a new method `messageSkipWaiting()` has been added to the `workbox-window` module to simplify the process of telling the "waiting" service worker to activate. And all "external" events in `workbox-window` have been removed in place of "normal" events with an `isExternal` property set to `true`. Thanks to both of the above changes, the "Offer a page reload for users" recipe can be simplified.
https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-v5
> Cleaner "Offer a page reload for users" recipe

- register.js
I am experimenting with `cacheOnFrontendNav`. I got the following results when using it in combination with dynamic pages (e.g. `./pages/[...uid].tsx`).
I don't know if this current change is the best way to do it. I don't know where to find documentation on the `arguments` array. It seems like the third array item is always correct. Haven't tested with query strings (not sure if this matters)
> fix: invalid dynamic nav url on cache

- cache.js
- examples/lifecycle/next.config.js
First off, I'd like to say that this is an amazing repo. 
I thought it would be a good idea to split the google font strategies so that we can have 1 for the style sheets & another for the font files themselves which don't change.
Ive based this PR off of this article https://developers.google.com/web/tools/workbox/guides/common-recipes#google_fonts
Let me know what you think, thanks
> split the google-fonts strategies

- examples/offline-fallback-v2/README.md
In React and TypeScript, `.ts` files are not valid components. The only way pages and components in React and Next.js with TypeScript are created is by using `.tsx` extension. 
For JavaScript it's fine
> Fixed a mistake in docs

- build-fallback-worker.js
> Fixed getFallbackEnvs pageExtensions param undefined

- README.md
Hello! First of all, thanks for this integration, really cool!
Since a few versions, Next.js has used the `public` folder - probably not necessary to keep the docs for the `static` folder in the readme anymore.
> Update instructions to use `public` folder

- build-custom-worker.js
- build-fallback-worker.js
These settings are more sensible. Without them my PWA with a custom worker fails to build, because it has dependencies who have dependencies that are universal modules that use some nodeJS builtins when they are available.
> Add node builtins fallback entries in webpack config

- index.js
Even after the update the middleware-manifest.json.json error was there. As it was in the server folder, the file name didn't match with the path.  So I just replace the filename ("middleware-manifest\.json") with the route ("server\/middleware-manifest\.json"). It fixed the problem (at least for me).
> Fix middleware-manifest.json.json error

- index.js
Fixing this annoying middlware precaching errors that pops up.
> Fixing middleware-runtime.js error

- index.js
Fixes the same issue as [#231](https://github.com/shadowwalker/next-pwa/issues/231)
All static media files are served from the `media` folder (this was changed in Next.js in https://github.com/vercel/next.js/pull/30168)
> fix double // for precache in static/media

- index.js
Fixed `buildExcludes` option not working at all
Here are some source code, 
``` javascript
exclude: [
({ asset, compilation }) => {
if (asset.name.match(/^(build-manifest\.json|react-loadable-manifest\.json|server\/middleware-manifest\.json|server\/middleware-runtime\.js|_middleware\.js|server\/pages\/_middleware\.js)$/)) {
return true
}
.....
return false
},
...buildExcludes
]
```
`exclude` options first element is function type, when pass to `workbox-webpack-plugin` apply checkCondition function. it always match first `if` condition. so that your `buildExcludes` with some string strategy or regex strategy will not match at all. on the other words `buildExcludes` not effect.
below is `workbox-webpack-plugin` source code
```typescript
function checkConditions(asset, compilation, …
```
> fixed buildExcludes options not working 

- README.md
This moves the steps at the bottom of the readme to the top since most users are on Next.js 9+ already.
> Update readme to assume Next.js 9 or newer

- index.js
With cacheStartUrl users can decide if they want to cache or not startUrl. It is the same as dynamicStartUrl but with dynamicStartUrl serviceWorker will send a request extra.
> Introduce an cacheStartUrl configuration

- build-custom-worker.js
- index.js
When `WorkboxPlugin.GenerateSW` is called it reads from the `importScripts` array. Webpack instance called from build-custom-worker.js appends to that array via the `success` callback. There is no guarantee that webpack compilation will finish before `GenerateSW` is called. This results in a bug where sometimes no scripts will be imported in the Service Worker code.
From my experiments to replicate this issue you need to ensure the webpack compilation is delayed enough. Then `GenerateSW` will not pick up any `importScripts`. For an example project triggering this bug see: https://github.com/errendir/next-pwa/tree/import-scripts-race-demo/examples/custom-worker
After running `yarn build`, please open the `public/sw.js` and format it with Prettier. You will find that no scripts have been …
> Avoid a race between reading from and writing to the `importScripts` array

- README.md
PWA url has migrated from [https://developers.google.com/](https://developers.google.com/web/ilt?hl=BG) to https://web.dev/learn/pwa/. Fixing the url in README.
> PWA doc migrated to web.dev

- index.js
In Next 12.2.3 a change was added saying that the `next.config.js` "must NOT have additional properties" and that the `pwa` property was considered as an additional property. Therefore, this commit deletes the `pwa` property from the calculated next config in the default exported function in index.js (aka the `withPWA` function). The returned next config therefore does not have the `pwa` field and the warning does not appear.
Resolves #367
> Remove pwa from withPWA return value

- index.js
In release 5.5.5 the disable option was broken. This fixes the option and allows it to work again.
Edit: Turns out all of the options specified do not work in 5.5.5. This should fix this.
Resolves: #371
Resolves: #370 
Resolves: #378
> Allows all PWA options to work
